"""add_soft_delete

Revision ID: e4b12d7ae0d3
Revises: 3e710b64d021
Create Date: 2026-03-12 17:44:23.656638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b12d7ae0d3'
down_revision: Union[str, None] = '3e710b64d021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
